In [27]:
import numpy as np

Array 1D

In [28]:
d1 = np.array([1, 2, 3])
print(d1)


[1 2 3]


In [29]:
d1.shape
#tamanho


(3,)

In [30]:
d1.ndim
#quantas dimensoes


1

In [31]:
d1.dtype

dtype('int64')

Array 2D

In [32]:
d2 = np.array([[1, 2, 3], [4, 5, 6]])
print(d2)


[[1 2 3]
 [4 5 6]]


In [33]:
d2.shape


(2, 3)

In [34]:
d2.ndim


2

In [35]:
d2.dtype


dtype('int64')

Array 3D

In [36]:
d3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(d3)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [37]:
d3.shape


(2, 2, 2)

In [38]:
d3.ndim


3

In [39]:
d3.dtype


dtype('int64')