In [19]:
import numpy as np

In [20]:
a = np.array([[2, 3, 4, 5],[6, 7, 8, 9]])
print(a)


[[2 3 4 5]
 [6 7 8 9]]


Para buscar o valor 8 nesse caso vamos na linha index 1 (segunda) row // e na coluna index 2 (terceira) colu

In [21]:
#Array[row, colu]
a[1,2]

np.int64(8)

Para uma row inteira

In [22]:
a[0,:]

array([2, 3, 4, 5])

valores especificos em rows diferentes

In [23]:
a[[0,1],[1,1]]

array([3, 7])

Para uma col inteira

In [24]:
a[:,1]

array([3, 7])